### ISSUE TITLE
Is plutil necessary?

### ISSUE THREAD

**Issue by ghost** [kabiroberai/theos-jailed#28]
I noticed the following line in the install script...

https://github.com/kabiroberai/theos-jailed/blob/3108b41e224ad48d9cb8ab1b6bef05ee804ae9b6/install#L26

As far as I know, iOS supports plists in both binary and XML formats. Any particular reason why binary plists are needed or preferred?

**Comment by kirb** [comment]
Binary is faster to parse.

**Comment by ghost** [comment]
Fair enough. If on-device iOS support is a goal, (mentioned by a separate GitHub issue) it might be worth checking out [CoreFoundation](https://opensource.apple.com/source/CF/CF-1153.18/) and compiling plconvert.c et al. from source.

**Comment by kirb** [comment]
Erica's plutil already supports this.

**Comment by kabiroberai** [comment]
The main reason for using plutil is that Cydia Impactor isn't able to parse NextStep style plists. For some reason the Substrate deb on Saurik's repo still uses that format, so I have to convert the plist to binary/XML for Impactor to function correctly.

As for porting Theos Jailed to iOS, let's discuss that in #9 instead of here.
